### ISSUE TITLE
[Bug] Chests play no animation when opening/closing

### ISSUE THREAD

**Issue by BLovegrove** [cyberanner/IronChests#2] opened 2021-07-09 10:21 UTC
Just what it says on the tin. Nothing appears in the log insofar as I can tell. Happens both standalone and in Valhelsia 1.17 pack (Where I first discovered it. 

Playing on MC 1.17 with Fabric Loader 0.11.6 and Fabric API 0.36.0+1.17

Don't make issue requests often so if there's any more info you need I apologize in advance and will be happy to provide it!

(edit: forgot to add steps to recreate - however in this case its literally just place any Iron Chest chest anywhere and interact with it)

**Comment by cyberanner** [comment] 2021-07-09 21:45
Nothing to apologize. Thanks for the report, however it is not a bug. The animation has not been implemented yet, I had to prioritize what to port before, and has the animation is just "aesthetics" I decided to work on the functional part first. I will work to implement it on a future release, as this is a planned feature.

**Comment by BLovegrove** [comment] 2021-07-10 10:55
Awesome - can't wait. Thanks for keeping this (imo very essential) mod updated and fabric-based!

**Comment by cyberanner** [comment] 2021-07-12 18:41
@BLovegrove I'm closing this issue as I've started working on implementing the animations. Expect this to be implemented in IronChests 1.2.0

**Closed by cyberanner** 2021-07-12 18:41 UTC
Labels: enhancement
